Question 5
---
What's wrong with the code?

```Ruby
limit = 15

def fib(first_num, second_num)
  while first_num + second_num < limit
    sum = first_num + second_num
    first_num = second_num
    second_num = sum
  end
  sum
end

result = fib(0, 1)
puts "result is #{result}"
```

My solution
---
An error is returned because method `fib` creates it's own inner scope and does not recognize `limit` from the outer scope as a variable within it's own scope. 

To fix this method, it's necessary to change `fib` to accept a new parameter `limit` and then pass the variable `limit` when invoking the function.

=> `limit` is not visible in the scope of `fib` because `fib` is a method and does not have access to any local variables outside of its scope.

Note
---
- to accept a new argument